In [2]:
import boto3
import pandas as pd
from io import StringIO

In [3]:
s3 = boto3.resource('s3')
bucket = s3.Bucket('xetra-1234')

In [12]:
bucket_obj1 = bucket.objects.filter(Prefix='2022-01-28/')
bucket_obj2 = bucket.objects.filter(Prefix='2022-03-15/')
objects = [obj for obj in bucket_obj1] + [obj for obj in bucket_obj2]

In [13]:
objects

[s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR00.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR01.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR02.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR03.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR04.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR05.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR06.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR07.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR08.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR09.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR10.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR11.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR12.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR13.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR14.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR15.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR16.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR17.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR18.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR19.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR20.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR21.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR22.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR23.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR00.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR01.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR02.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR03.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR04.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR05.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR06.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR07.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR08.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR09.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR10.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR11.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR12.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR13.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR14.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR15.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR16.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR17.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR18.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR19.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR20.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR21.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR22.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-03-15/2022-03-15_BINS_XETR23.csv')]

In [14]:
csv_obj_init = bucket.Object(key= objects[0].key).get().get('Body').read().decode('utf-8')
data = StringIO(csv_obj_init)
df_init = pd.read_csv(data, delimiter=',')

In [16]:
df_init.columns

Index(['ISIN', 'Mnemonic', 'SecurityDesc', 'SecurityType', 'Currency',
       'SecurityID', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice',
       'EndPrice', 'TradedVolume', 'NumberOfTrades'],
      dtype='object')

In [20]:
df_all = pd.DataFrame(columns=df_init.columns)
for obj in objects:
    csv_obj = bucket.Object(key= obj.key).get().get('Body').read().decode('utf-8')
    data = StringIO(csv_obj)
    df = pd.read_csv(data, delimiter=',')
    df_all = df_all.append(df, ignore_index=True)

In [19]:
df_all

,ISIN,Mnemonic,SecurityDesc,SecurityType,Currency,SecurityID,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume,NumberOfTrades
0,AT0000A0E9W5,SANT,S+T AG O.N.,Common stock,EUR,2504159,2022-01-28,08:00,16.39,16.44,16.39,16.44,3249,4
1,DE000A0DJ6J9,S92,SMA SOLAR TECHNOL.AG,Common stock,EUR,2504287,2022-01-28,08:00,31.30,31.30,30.98,31.02,13383,24
2,DE000A0D6554,NDX1,NORDEX SE O.N.,Common stock,EUR,2504290,2022-01-28,08:00,13.26,13.32,13.26,13.30,12572,29
3,DE000A0D9PT0,MTX,MTU AERO ENGINES NA O.N.,Common stock,EUR,2504297,2022-01-28,08:00,190.45,190.45,189.55,190.05,1413,26
4,DE000A0HN5C6,DWNI,DEUTSCHE WOHNEN SE INH,Common stock,EUR,2504314,2022-01-28,08:00,35.65,35.74,35.65,35.74,414,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250458,US5261071071,LXI,"LENNOX INTL INC. DL-,01",Common stock,EUR,5990171,2022-03-15,20:30,238.00,238.00,238.00,238.00,0,1
250459,US9553061055,WPS,"WEST PHARM.SVCS DL-,25",Common stock,EUR,6001426,2022-03-15,20:30,333.20,333.20,333.20,333.20,0,1
250460,US02208R1068,XQB,"ALTRA INDL MOTION DL-,001",Common stock,EUR,6014094,2022-03-15,20:30,35.20,35.20,35.20,35.20,0,1
250461,DE000A3MQCP7,FMEN,FRESEN.MED.CARE O.N. NEUE,Common stock,EUR,7290694,2022-03-15,20:30,55.00,55.00,55.00,55.00,0,1
250462,DE000A3MQDG4,BIO2,BIOTEST AG ST ANGEDIENT.,Common stock,EUR,7335008,2022-03-15,20:30,40.60,40.60,40.60,40.60,0,1

In [21]:
columns = ['ISIN', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice','EndPrice', 'TradedVolume']
df_all = df_all.loc[:, columns]

In [ ]:
df_all

In [9]:
df

,ISIN,Mnemonic,SecurityDesc,SecurityType,Currency,SecurityID,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume,NumberOfTrades
0,AT0000A0E9W5,SANT,S+T AG O.N.,Common stock,EUR,2504159,2022-01-28,08:00,16.390,16.440,16.39,16.44,3249,4
1,DE000A0DJ6J9,S92,SMA SOLAR TECHNOL.AG,Common stock,EUR,2504287,2022-01-28,08:00,31.300,31.300,30.98,31.02,13383,24
2,DE000A0D6554,NDX1,NORDEX SE O.N.,Common stock,EUR,2504290,2022-01-28,08:00,13.260,13.320,13.26,13.30,12572,29
3,DE000A0D9PT0,MTX,MTU AERO ENGINES NA O.N.,Common stock,EUR,2504297,2022-01-28,08:00,190.450,190.450,189.55,190.05,1413,26
4,DE000A0HN5C6,DWNI,DEUTSCHE WOHNEN SE INH,Common stock,EUR,2504314,2022-01-28,08:00,35.650,35.740,35.65,35.74,414,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16728,DK0061539921,VWSB,"VESTAS WIND SYS. DK -,20",Common stock,EUR,6354987,2022-01-28,08:59,23.270,23.270,23.27,23.27,37,1
16729,DE000A3E5D56,FPE,FUCHS PETROLUB NA ST O.N.,Common stock,EUR,6699157,2022-01-28,08:59,30.060,30.080,30.06,30.08,218,3
16730,DE000A3E5D64,FPE3,FUCHS PETROLUB VZO NA ON,Common stock,EUR,6699158,2022-01-28,08:59,38.100,38.100,38.10,38.10,34,1
16731,FR0000121147,FAU,FAURECIA EU INH EO 7,Common stock,EUR,7026036,2022-01-28,08:59,38.840,38.840,38.84,38.84,40,1
16732,DE000DTR0CK8,DTG,DAIMLER TRUCK HLDG JGE NA,Common stock,EUR,7126155,2022-01-28,08:59,31.925,31.925,31.91,31.92,1461,10